In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("hr_attrition_cleaned.xlsx")

In [3]:
df.head()

,employee_id,Name,gender,age,DOB,marital_status,department,job_role,education_level,education_field,...,training_times_last_year,num_companies_worked,promotion_last_years,distance_from_home,business_travel,city,manager_name,attrition,reason_for_leaving,exit_date
0,EMP1784,Jacob Thompson,Male,24,1997-04-07,Divorced,Research & Development,Data Analyst,5,Human Resources,...,0.0,NaN,2,36.3,travel_frequently,Matthewmouth,Eric Charles,Yes,Better Opportunity,30/01/2022
1,EMP1198,Randy Morris,M,45,03-28-1994,Single,Human Resources,HR Manager,5,Life Sciences,...,5.0,3.0,1,NaN,Travel_Rarely,North Joseph,Steven Aguilar,No,NaN,NaN
2,EMP2052,Teresa Jordan,Female,56,1988-10-05,Married,Human Resources,HR Executive,4,Marketing,...,0.0,0.0,2,NaN,Travel_Rarely,Burnettbury,David Sharp,No,NaN,NaN
3,EMP1070,Amanda Johnson,M,23,1968-02-15,Married,Human Resources,HR Manager,5,Business,...,0.0,NaN,0,NaN,Non-Travel,Jamesland,Gina Nelson,No,NaN,NaN
4,EMP2183,Todd Frazier,Female,45,NaN,Divorced,Human Resources,HR Executive,1,Technical Degree,...,NaN,5.0,0,10.7,Non-Travel,New Jeffrey,Stephanie Rodriguez,No,NaN,NaN

In [4]:
df.shape

(1513, 29)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               1513 non-null   object
 1   Name                      1513 non-null   object
 2   gender                    1314 non-null   object
 3   age                       1513 non-null   int64
 4   DOB                       1438 non-null   object
 5   marital_status            1351 non-null   object
 6   department                1513 non-null   object
 7   job_role                  1513 non-null   object
 8   education_level           1513 non-null   int64
 9   education_field           1304 non-null   object
 10  hire_date                 1513 non-null   object
 11  years_at_company          1513 non-null   int64
 12  monthly_salary            1435 non-null   float64
 13  hourly_rate               1513 non-null   float64
 14  overtime                  1318 non-null   object
 15  performance_rating        1292 non-null   float64
 16  job_satisfaction          1202 non-null   float64
 17  environment_satisfaction  1207 non-null   float64
 18  work_life_balance         1211 non-null   float64
 19  training_times_last_year  1266 non-null   float64
 20  num_companies_worked      1322 non-null   float64
 21  promotion_last_years      1513 non-null   int64
 22  distance_from_home        759 non-null    float64
 23  business_travel           1308 non-null   object
 24  city                      1513 non-null   object
 25  manager_name              1513 non-null   object
 26  attrition                 1513 non-null   object
 27  reason_for_leaving        226 non-null    object
 28  exit_date                 235 non-null    object
dtypes: float64(9), int64(4), object(16)
memory usage: 342.9+ KB

In [6]:
df.describe()

,age,education_level,years_at_company,monthly_salary,hourly_rate,performance_rating,job_satisfaction,environment_satisfaction,work_life_balance,training_times_last_year,num_companies_worked,promotion_last_years,distance_from_home
count,1513.000000,1513.000000,1513.000000,1435.000000,1513.000000,1292.000000,1202.000000,1207.000000,1211.000000,1266.000000,1322.000000,1513.000000,759.000000
mean,36.986781,2.990086,5.003966,63977.721254,65.345340,3.792570,2.500832,2.553438,2.503716,2.474724,2.969743,1.442168,20.185903
std,16.382896,1.409260,2.571719,33435.371834,20.179924,2.246334,1.139883,1.099639,1.109960,1.665196,1.993325,1.104701,11.215039
min,-5.000000,1.000000,1.000000,-5000.000000,30.090000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.100000
25%,28.000000,2.000000,3.000000,37950.000000,47.820000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,0.000000,10.350000
50%,39.000000,3.000000,5.000000,65200.000000,65.630000,3.000000,2.000000,3.000000,3.000000,2.000000,3.000000,1.000000,19.800000
75%,50.000000,4.000000,7.000000,91700.000000,82.820000,5.000000,4.000000,4.000000,3.000000,4.000000,5.000000,2.000000,30.000000
max,60.000000,5.000000,10.000000,120000.000000,100.000000,8.000000,4.000000,4.000000,4.000000,5.000000,6.000000,3.000000,40.000000

In [7]:
df.isnull().sum()

employee_id                    0
Name                           0
gender                       199
age                            0
DOB                           75
marital_status               162
department                     0
job_role                       0
education_level                0
education_field              209
hire_date                      0
years_at_company               0
monthly_salary                78
hourly_rate                    0
overtime                     195
performance_rating           221
job_satisfaction             311
environment_satisfaction     306
work_life_balance            302
training_times_last_year     247
num_companies_worked         191
promotion_last_years           0
distance_from_home           754
business_travel              205
city                           0
manager_name                   0
attrition                      0
reason_for_leaving          1287
exit_date                   1278
dtype: int64

In [8]:
df['employee_id'].unique()

array(['EMP1784', 'EMP1198', 'EMP2052', ..., 'EMP1969', 'EMP1953',
       'EMP2274'], shape=(1500,), dtype=object)

In [ ]:
#Key Formulas for HR Attrition
# Attrition Rate:

# Attrition Rate = Employees Left/Total Employees×100

In [9]:
attrition_rate = (df['attrition'].value_counts()['Yes']/len(df)) * 100

In [10]:
df['age'].mean()

np.float64(36.986781229345674)

In [11]:
df['monthly_salary'].mean()

np.float64(63977.7212543554)

In [12]:
df['years_at_company'].mean()

np.float64(5.003965631196299)

In [13]:
#Group Analysis (e.g., attrition by department):

In [14]:
df.groupby('department')['attrition'].value_counts(normalize=True)

department              attrition
Finance                 No           0.804167
                        Yes          0.195833
Human Resources         No           0.847328
                        Yes          0.152672
IT                      No           0.833333
                        Yes          0.166667
Marketing               No           0.804979
                        Yes          0.195021
Research & Development  No           0.819549
                        Yes          0.180451
Sales                   No           0.821138
                        Yes          0.178862
Name: proportion, dtype: float64

In [ ]:
# ---- 1. Rename ----

In [16]:
df = df.rename(columns={"Name":"employee_name"})
print(df.columns.tolist())

['employee_id', 'employee_name', 'gender', 'age', 'DOB', 'marital_status', 'department', 'job_role', 'education_level', 'education_field', 'hire_date', 'years_at_company', 'monthly_salary', 'hourly_rate', 'overtime', 'performance_rating', 'job_satisfaction', 'environment_satisfaction', 'work_life_balance', 'training_times_last_year', 'num_companies_worked', 'promotion_last_years', 'distance_from_home', 'business_travel', 'city', 'manager_name', 'attrition', 'reason_for_leaving', 'exit_date']

In [ ]:
# ---- 2. Fix data types ----

In [18]:
df["hire_date"] = pd.to_datetime(df["hire_date"],errors="coerce")
df["hire_date"].isna().sum()

np.int64(1135)

In [19]:
df['DOB'].dtype #check type

dtype('O')

In [20]:
df["DOB"] = pd.to_datetime(df["DOB"],errors="coerce")
df["exit_date"] = pd.to_datetime(df["exit_date"], errors="coerce",dayfirst=True)
print(df["DOB"].isna().sum())

1110

In [21]:
# ---- 3. Standardize text/categorical casing FIRST (before filling, so fills match clean categories) ----
df["employee_name"] = df["employee_name"].str.strip().str.title()
df["attrition"] = df["attrition"].str.strip().str.title()
df["gender"] = df["gender"].replace({"M": "Male", "m": "Male", "MALE": "Male",
                                       "F": "Female", "f": "Female", "FEMALE": "Female"})
df["overtime"] = df["overtime"].replace({"Y": "Yes", "yes": "Yes", "N": "No", "no": "No"})
df["marital_status"] = df["marital_status"].str.strip().str.title()
df["business_travel"] = df["business_travel"].str.strip().str.title()

In [ ]:
# ---- 4. Fix invalid numeric values (business-logic errors) ----

In [22]:
median_age = df.loc[(df["age"] > 18) & (df["age"] < 65), "age"].median()
df["age"] = df["age"].apply(lambda x: median_age if (x <= 18 or x >= 65) else x)

In [23]:
df["performance_rating"] = df["performance_rating"].where(df["performance_rating"].between(1,5))
df["monthly_salary"] = df["monthly_salary"].where(df["monthly_salary"] > 0)

In [ ]:
# ---- 5. Fill missing values — grouped/logical imputation ----

In [24]:
df["monthly_salary"] = df["monthly_salary"].fillna(
    df.groupby("job_role")["monthly_salary"].transform("median"))

In [25]:
df["education_field"] = df["education_field"].fillna(
    df.groupby("job_role")["education_field"].transform(lambda x: x.mode()[0] if not x.mode().empty else "Unknown"))

In [26]:
df["distance_from_home"] = df["distance_from_home"].fillna(
    df.groupby("city")["distance_from_home"].transform("median"))

In [27]:
df["performance_rating"] = df["performance_rating"].fillna(df["performance_rating"].median())

In [28]:
df["training_times_last_year"] = df["training_times_last_year"].fillna(df["training_times_last_year"].median())

In [29]:
df["num_companies_worked"] = df["num_companies_worked"].fillna(df["num_companies_worked"].median())

In [30]:
df["overtime"] = df["overtime"].fillna(df["overtime"].mode()[0])
df["business_travel"] = df["business_travel"].fillna(df["business_travel"].mode()[0])

In [31]:
# ---- 6. Fill values that genuinely can't be recovered — mark explicitly, don't guess ----

In [32]:
df["gender"] = df["gender"].fillna("Not Disclosed")

In [33]:
df["marital_status"] = df["marital_status"].fillna("Not Disclosed")

In [34]:
# ---- 7. Leave subjective survey scores as-is, but flag rows missing them ----

In [35]:
survey_cols = ["job_satisfaction", "environment_satisfaction", "work_life_balance"]
df["missing_survey_data"] = df[survey_cols].isna().any(axis=1)

In [36]:
# ---- 9. Remove duplicates ----

In [37]:
df = df.drop_duplicates()
df["duplicate_emp_id"] = df["employee_id"].duplicated(keep = False)

In [38]:
# ---- 10. Feature engineering ----

In [39]:
df["age_group"] = pd.cut(df["age"], bins=[18, 25, 35, 45, 65], labels=["18-25", "26-35", "36-45", "46-65"])
df["tenure_group"] = pd.cut(df["years_at_company"], bins=[-1, 1, 3, 6, 20], labels=["<1yr", "1-3yr", "3-6yr", "6+yr"])

In [40]:
# ---- 11. Final check ----
print("Remaining missing values:\n", df.isna().sum())

Remaining missing values:
 employee_id                    0
employee_name                  0
gender                         0
age                            0
DOB                         1110
marital_status                 0
department                     0
job_role                       0
education_level                0
education_field                0
hire_date                   1135
years_at_company               0
monthly_salary                 0
hourly_rate                    0
overtime                       0
performance_rating             0
job_satisfaction             311
environment_satisfaction     306
work_life_balance            302
training_times_last_year       0
num_companies_worked           0
promotion_last_years           0
distance_from_home           702
business_travel                0
city                           0
manager_name                   0
attrition                      0
reason_for_leaving          1287
exit_date                   1459
missing_survey_data            0
duplicate_emp_id               0
age_group                      0
tenure_group                   0
dtype: int64

In [ ]:
df.isna().sum()

In [41]:
df = df.replace(["", " ", "null", "NULL", "None", "N/A", "NaN", "nan"], np.nan)

In [42]:
df["gender"] = df["gender"].fillna("Not Disclosed")
df["marital_status"] = df["marital_status"].fillna("Not Disclosed")

In [43]:
df["age"] = df["age"].apply(lambda x: median_age if pd.isna(x) or x <= 18 or x >= 65 else x)

In [44]:
df.isna().sum()
df.eq("null").sum()
df.eq("NULL").sum()

employee_id                 0
employee_name               0
gender                      0
age                         0
DOB                         0
marital_status              0
department                  0
job_role                    0
education_level             0
education_field             0
hire_date                   0
years_at_company            0
monthly_salary              0
hourly_rate                 0
overtime                    0
performance_rating          0
job_satisfaction            0
environment_satisfaction    0
work_life_balance           0
training_times_last_year    0
num_companies_worked        0
promotion_last_years        0
distance_from_home          0
business_travel             0
city                        0
manager_name                0
attrition                   0
reason_for_leaving          0
exit_date                   0
missing_survey_data         0
duplicate_emp_id            0
age_group                   0
tenure_group                0
dtype: int64

In [45]:
df.to_csv("hr_attrition_clean.csv", index=False)